{
 "title": "COMPARE BY VERSION",
 "tags": [
  "influxdb",
  "jmeter"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\")\n|> keyValues(keyColumns: [\"application\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "env",
    "label": "env",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\")\n|> keyValues(keyColumns: [\"env\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "test",
    "label": "test",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\")\n|> keyValues(keyColumns: [\"test\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "duration",
    "label": "duration",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\"  and r.test == \"[[test:raw]]\")\n|> keyValues(keyColumns: [\"duration\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "users",
    "label": "users",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\" and r.test == \"[[test:raw]]\" and r.duration == \"[[duration]]\")\n|> keyValues(keyColumns: [\"users\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "version",
    "label": "version",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\" and r.test == \"[[test:raw]]\" and r.duration == \"[[duration]]\" and r.users == \"[[users]]\")\n|> keyValues(keyColumns: [\"version\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   { "name": "tx", "label": "tx", "query": ".+" }
  ]
 },
 "panels": [
  {
   "title": "latency (ms)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"avg\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> mean()\n  |> rename(columns: {_value: \"avg\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"min\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> min()\n  |> rename(columns: {_value: \"min\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"max\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> max()\n  |> rename(columns: {_value: \"max\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> mean()\n  |> rename(columns: {_value: \"avg pct99\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> min()\n  |> rename(columns: {_value: \"min pct99\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> max()\n  |> rename(columns: {_value: \"max pct99\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "throughput (op/s)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"count\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> mean()\n  |> rename(columns: {_value: \"avg\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"count\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> max()\n  |> rename(columns: {_value: \"max\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"count\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> quantile(q: 0.99)\n  |> mean()\n  |> rename(columns: {_value: \"avg pct99\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"sb\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> sum()\n  |> rename(columns: {_value: \"sent\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"]  == \"rb\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r[\"transaction\"] =~ /^${tx}$/  and r.application == \"${app}\" and r.env == \"${env}\"  and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"version\"])\n  |> group(columns: [\"transaction\",\"version\"])\n  |> sum()\n  |> rename(columns: {_value: \"received\"})\n  |> group()"
    }
   ]
  }
 ]
}