{
 "title": "EXPLORE",
 "description": "Monitor your Apache JMeter load test in real time with InfluxDB and Grafana.\r\nGet overall summary, errors details and particular transaction response times.",
 "tags": [
  "jmeter",
  "influxdb"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\")\n|> keyValues(keyColumns: [\"application\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "env",
    "label": "env",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\")\n|> keyValues(keyColumns: [\"env\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "version",
    "label": "version",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\")\n|> keyValues(keyColumns: [\"version\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "test",
    "label": "test",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\"  and r.version == \"[[version:raw]]\")\n|> keyValues(keyColumns: [\"test\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "duration",
    "label": "duration",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\"  and r.version == \"[[version:raw]]\" and r.test == \"[[test:raw]]\")\n|> keyValues(keyColumns: [\"duration\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "users",
    "label": "users",
    "query": "from(bucket: \"mighty-meter\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r._measurement == \"statistics\" and r.application == \"[[app:raw]]\" and r.env == \"[[env:raw]]\"  and r.version == \"[[version:raw]]\" and r.test == \"[[test:raw]]\" and r.duration == \"[[duration]]\")\n|> keyValues(keyColumns: [\"users\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   { "name": "qtest", "label": "search", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n|> range(start: -100y)\n|> filter(fn: (r) => r._measurement == \"events\" and (r._value =~ /started/ or r._value =~ /ended/) and (r._value =~ /${qtest}/ or r.application =~ /${qtest}/ or r.env =~ /${qtest}/ ))\n|> keep(columns: [\"_value\",\"application\",\"env\",\"duration\",\"users\",\"version\",\"_time\"])\n|> group()\n |> rename(columns: {_time: \"start\", _value: \"event\", duration: \"duration (sg)\"})"
    }
   ]
  },
  { "title": "Stats (all tx)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\" and  r[\"statut\"] == \"ok\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  =~ /count/ and r[\"transaction\"] == \"all\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_value\",\"_time\",\"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |>  reduce(fn: (r, accumulator) => (\n        {count: r.count + accumulator.count, \n         countError: r.countError + accumulator.countError\n        }\n        ), \n        identity: {count: 0.0, countError: 0.0})\n    |> map(fn: (r) => ({ r with _value: (r.count / (r.countError + r.count)) }))\n    |> keep(columns: [\"_value\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\"  and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> mean()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"min\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> min()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> max()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\" and  r[\"statut\"] == \"ko\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  =~ /count/ and r[\"transaction\"] == \"all\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_value\",\"_time\",\"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |>  reduce(fn: (r, accumulator) => (\n        {count: r.count + accumulator.count, \n         countError: r.countError + accumulator.countError\n        }\n        ), \n        identity: {count: 0.0, countError: 0.0})\n    |> map(fn: (r) => ({ r with _value: (r.countError / (r.countError + r.count)) }))\n    |> keep(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rb\" and  r[\"transaction\"] == \"all\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> sum()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sb\" and  r[\"transaction\"] == \"all\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> sum()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pct99",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pct99.0\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> mean()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "throughput (op/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"count\"  and r[\"transaction\"]  == \"all\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"application\",\"_time\",\"_value\",\"env\",\"version\",\"users\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"maxAT\" and r[\"transaction\"] == \"internal\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"application\",\"_time\",\"_value\",\"env\",\"version\",\"users\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Stats (per tx)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "throughput (op/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"count\" and r[\"statut\"]  == \"all\" and r[\"transaction\"]  != \"all\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\",\"_time\"])\n  |> group(columns: [\"transaction\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "latency (ms)",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"avg\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\" and r.application == \"${app}\" and r.env == \"${env}\" and r.version == \"${version}\" and r.test == \"${test}\" and r.duration == \"${duration}\" and r.users == \"${users}\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> mean()\n  |> rename(columns: {_value: \"avg\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"min\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> min()\n  |> group()\n  |> rename(columns: {_value: \"min\"})\n"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"max\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> max()\n  |> group()\n  |> rename(columns: {_value: \"max\"})\n"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> mean()\n  |> group()\n  |> rename(columns: {_value: \"avg pct99\"})"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> min()\n  |> group()\n  |> rename(columns: {_value: \"min pct99\"})"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> max()\n  |> group()\n  |> rename(columns: {_value: \"max pct99\"})\n"
    }
   ]
  },
  {
   "title": "bytes",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"sb\" and r[\"statut\"] != \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> sum()\n  |> group()\n  |> rename(columns: {_value: \"sent\"})"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"rb\" and r[\"statut\"] != \"all\" )\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> sum()\n  |> group()\n  |> rename(columns: {_value: \"received\"})"
    }
   ]
  }
 ]
}