{
 "title": "REALTIME",
 "description": "Monitor your Apache JMeter load test in real time with InfluxDB and Grafana.\r\nGet overall summary, errors details and particular transaction response times.",
 "tags": [
  "jmeter",
  "influxdb"
 ],
 "time": { "from": "now-120m", "to": "now" },
 "refresh": true,
 "panels": [
  { "title": "Stats (all tx)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\" and  r[\"statut\"] == \"ok\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  =~ /count/ and r[\"transaction\"] == \"all\")\n  |> keep(columns: [\"_value\",\"_time\",\"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |>  reduce(fn: (r, accumulator) => (\n        {count: r.count + accumulator.count, \n         countError: r.countError + accumulator.countError\n        }\n        ), \n        identity: {count: 0.0, countError: 0.0})\n    |> map(fn: (r) => ({ r with _value: ((r.count - r.countError) /  r.count) }))\n    |> keep(columns: [\"_value\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> mean()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"min\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> min()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> max()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\" and  r[\"statut\"] == \"ko\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  =~ /count/ and r[\"transaction\"] == \"all\")\n  |> keep(columns: [\"_value\",\"_time\",\"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |>  reduce(fn: (r, accumulator) => (\n        {count: r.count + accumulator.count, \n         countError: r.countError + accumulator.countError\n        }\n        ), \n        identity: {count: 0.0, countError: 0.0})\n    |> map(fn: (r) => ({ r with _value: (r.countError / r.count) }))\n    |> keep(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rb\" and  r[\"transaction\"] == \"all\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> sum()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sb\" and  r[\"transaction\"] == \"all\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> sum()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pct99",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pct99.0\")\n  |> keep(columns: [\"_field\",\"_time\",\"_value\"])\n  |> mean()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "throughput (op/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"count\"  and r[\"transaction\"]  == \"all\" )\n  |> keep(columns: [\"application\",\"_time\",\"_value\",\"env\",\"version\",\"users\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"maxAT\" and r[\"transaction\"] == \"internal\")\n  |> keep(columns: [\"application\",\"_time\",\"_value\",\"env\",\"version\",\"users\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Stats (per tx)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "throughput (op/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"count\" and r[\"statut\"]  == \"all\" and r[\"transaction\"]  != \"all\" )\n  |> keep(columns: [\"transaction\",\"_value\",\"_time\"])\n  |> group(columns: [\"transaction\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "latency (ms)",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"avg\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> mean()\n  |> rename(columns: {_value: \"avg\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"min\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> min()\n  |> group()\n  |> rename(columns: {_value: \"min\"})\n"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"max\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> max()\n  |> group()\n  |> rename(columns: {_value: \"max\"})\n"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> mean()\n  |> group()\n  |> rename(columns: {_value: \"avg pct99\"})"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> min()\n  |> group()\n  |> rename(columns: {_value: \"min pct99\"})"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"pct99.0\" and r[\"statut\"]  == \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> max()\n  |> group()\n  |> rename(columns: {_value: \"max pct99\"})\n"
    }
   ]
  },
  {
   "title": "bytes",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"sb\" and r[\"statut\"] != \"all\" and r[\"transaction\"] != \"all\")\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> sum()\n  |> group()\n  |> rename(columns: {_value: \"sent\"})"
    },
    {
     "query": "from(bucket: \"mighty-meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"rb\" and r[\"statut\"] != \"all\" )\n  |> keep(columns: [\"transaction\",\"_value\"])\n  |> group(columns: [\"transaction\"])\n  |> sum()\n  |> group()\n  |> rename(columns: {_value: \"received\"})"
    }
   ]
  }
 ]
}